app:
  port: 9000

database:
  uri: admin:password@tcp(localhost:3306)/gin_sample?charset=utf8mb4&parseTime=True
  time_out: 30
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_life_time:
  debug: true

